initial planning for 2.0.0 release

diff --git a/bin/bashpwdm_udpate b/bin/bashpwdm_udpate
--- a/bin/bashpwdm_udpate
+++ b/bin/bashpwdm_udpate
@@ -13,8 +13,8 @@ last_version=$(cd /tmp && wget --no-check-certificate https://raw.github.com/pol
 
 function update_bashpwdm(){
 if [ $(id -u) != "0" ]; then 
- echo "  * ERROR: please run update script as ROOT!\n"
- exit 1
+  echo "  * ERROR: please run update script as ROOT!\n"
+  exit 1
 fi
 echo "  * Write your exact username:"
 read username
@@ -22,24 +22,24 @@ echo "  * Checking Bash PWD Manager version..."
 echo -ne "    Your version is $version
     Newest version is $last_version\n"
 if [ "$version" != "$last_version" ] ; then
-echo "  * Updating Bash PWD Manager, please wait..."
-cd /tmp && mkdir bashpwdm_tmp
-cd bashpwdm_tmp && wget https://github.com/downloads/polslinux/BashPWDManager/bashpwdm_v$last_version.tar.bz2 &>/dev/null
-tar -xjf bashpwdm_v$last_version.tar.bz2
-cp LICENSE uninstall docs/* /usr/share/doc/bash-pwd-manager
-cp bin/bashpwdm /usr/local/bin
-cp bin/bashpwdm-config /usr/local/bin
-cp bin/bashpwdm_udpate /usr/local/bin
-chown $username /usr/local/bin/bashpwdm
-chown $username /usr/local/bin/bashpwdm-config
-chown $username /usr/local/bin/bashpwdm_update
-chmod +x /usr/local/bin/bashpwdm
-chmod +x /usr/local/bin/bashpwdm-config
-chmod +x /usr/local/bin/bashpwdm_update
-cd .. && rm -r bashpwdm_tmp && rm -f bashpwdm_v$last_version.tar.bz2
-echo "  * All done, Bash PWD Manager has been updated :)"
+  echo "  * Updating Bash PWD Manager, please wait..."
+  cd /tmp && mkdir bashpwdm_tmp
+  cd bashpwdm_tmp && wget https://github.com/downloads/polslinux/BashPWDManager/bashpwdm_v$last_version.tar.bz2 &>/dev/null
+  tar -xjf bashpwdm_v$last_version.tar.bz2
+  cp LICENSE uninstall docs/* /usr/share/doc/bash-pwd-manager
+  cp bin/bashpwdm /usr/local/bin
+  cp bin/bashpwdm-config /usr/local/bin
+  cp bin/bashpwdm_udpate /usr/local/bin
+  chown $username /usr/local/bin/bashpwdm
+  chown $username /usr/local/bin/bashpwdm-config
+  chown $username /usr/local/bin/bashpwdm_update
+  chmod +x /usr/local/bin/bashpwdm
+  chmod +x /usr/local/bin/bashpwdm-config
+  chmod +x /usr/local/bin/bashpwdm_update
+  cd .. && rm -r bashpwdm_tmp && rm -f bashpwdm_v$last_version.tar.bz2
+  echo "  * All done, Bash PWD Manager has been updated :)"
 elif [ "$version" = "$last_version" ] ; then
-echo "  * Bash PWD Manager is already up-to-date"
+  echo "  * Bash PWD Manager is already up-to-date"
 fi
 }
 
