lot of improvements, see changelog and test bashpwdm

diff --git a/install b/install
--- a/install
+++ b/install
@@ -9,10 +9,6 @@
 ################################################################
 
 distro=$(cat /etc/issue | cut -d' ' -f1 -s)
-pkg1=`which zenity`
-pkg2=`which bash`
-pkg3=`which gpg`
-pkg4=`which pinentry-gtk-2`
 
 echo -ne "* Checking user's privileges...\n"
 if [ "$(id -u)" != "0" ]; then 
@@ -35,16 +31,36 @@ else
 	echo  "   try it on your system and tell me if there is something wrong!"
 fi
 
-echo -ne "* Checking deps...\n"
-if [ "$pkg1" == "/usr/bin/zenity" ] && [ "$pkg2" == "/bin/bash" ] && [ "$pkg3" == "/usr/bin/gpg" ] && [ "$pkg4" == "/usr/bin/pinentry-gtk-2" ] ; then
-	echo -ne "  Deps are ok...\n"
-	else
-		echo -ne "* ERROR: you have to install zenity, gpg, bash and pinentry-gtk2 before you"
-		echo -ne "  can you this script!\n"
-		exit 1
+echo "* Checking deps..."
+pkg1=`which zenity`
+if [ $? == 0 ] ; then
+pkg1_ver=`zenity --version | sed 's/[^0-9]*//g'`
+ if [ $pkg1_ver -lt 315 ] ; then
+   echo "ERROR: Zenity version MUST be > 3.1.5"
+   exit 1
+ fi
+elif [ $? != 0 ] ; then
+echo "--> ERROR: You have to install zenity before continue..."
+exit 1
 fi
+pkg2=`which bash`
+if [ $? != 0 ] ; then
+echo "--> ERROR: You have to install bash before continue..."
+exit 1
+fi
+pkg3=`which gpg`
+if [ $? != 0 ] ; then
+echo "--> ERROR: You have to install gpg before continue..."
+exit 1
+fi
+pkg4=`which pinentry-gtk-2`
+if [ $? != 0 ] ; then
+echo "--> ERROR: You have to install pinentry-gtk2 before continue..."
+exit 1
+fi
+echo -ne"OK!\n"
 
-echo -ne "* Installing files...\n"
+echo "* Installing files..."
 if [ ! -d /usr/share/doc/bash-pwd-manager ] ; then
 	mkdir /usr/share/doc/bash-pwd-manager
 fi
@@ -57,5 +73,5 @@ chown $username /usr/local/bin/bashpwdm
 chown $username /usr/local/bin/bashpwdm-config
 chmod +x /usr/local/bin/bashpwdm
 chmod +x /usr/local/bin/bashpwdm-config
-echo "   All done! :)"
+echo -ne "OK!\n"
 exit 0
