1.1.0-alpha1: see changelog for info

diff --git a/install b/install
--- a/install
+++ b/install
@@ -59,6 +59,11 @@ if [ $? != 0 ] ; then
 echo "--> ERROR: You have to install pinentry-gtk2 before continue..."
 exit 1
 fi
+pkg5=`which openssl`
+if [ $? != 0 ] ; then
+echo "--> ERROR: You have to install openssl before continue..."
+exit 1
+fi
 echo -ne "   Ok!\n"
 
 echo "* Installing files..."
