minor changes

diff --git a/install b/install
--- a/install
+++ b/install
@@ -33,15 +33,15 @@ fi
 
 echo "* Checking deps..."
 pkg1=`which zenity`
-if [ $? == 0 ] ; then
+if [ $? != 0 ] ; then
+ echo "--> ERROR: You have to install zenity before continue..."
+ exit 1
+else
 pkg1_ver=`zenity --version | sed 's/[^0-9]*//g'`
  if [ $pkg1_ver -lt 315 ] ; then
    echo "ERROR: Zenity version MUST be > 3.1.5"
    exit 1
  fi
-elif [ $? != 0 ] ; then
-echo "--> ERROR: You have to install zenity before continue..."
-exit 1
 fi
 pkg2=`which bash`
 if [ $? != 0 ] ; then
@@ -58,7 +58,7 @@ if [ $? != 0 ] ; then
 echo "--> ERROR: You have to install pinentry-gtk2 before continue..."
 exit 1
 fi
-echo -ne"OK!\n"
+echo -ne "OK!\n"
 
 echo "* Installing files..."
 if [ ! -d /usr/share/doc/bash-pwd-manager ] ; then
